### ISSUE TITLE
Em khong build duoc!!!

### ISSUE THREAD

**Issue by thecursehunter** [fcitx/fcitx5-bamboo#7]
- Em da tai Fcitx bang apt, va go bang snap, sau do clone repo nay, roi chay cac command theo huong dan gom:

1. $ mkdir build && cd build
2. $ cmake -DCMAKE_INSTALL_PREFIX=[prefix to fcitx5] ..

- roi em nhan duoc loi nay: 

![image](https://user-images.githubusercontent.com/73272262/218133553-253d1ed5-e641-4f03-8876-6930c0fccc07.png)

**Comment by hmtheboy154** [comment]
`[prefix to fcitx5]` không phải là một directory, bạn có thể thử ` cmake -DCMAKE_INSTALL_PREFIX=/`
và đừng quên đây là fcitx5 nhé, không phải fcitx đâu.....

Ubuntu có fcitx5-bamboo từ 22.10 đấy

**Comment by thecursehunter** [comment]
> `[prefix to fcitx5]` không phải là một directory, bạn có thể thử ` cmake -DCMAKE_INSTALL_PREFIX=/`
> và đừng quên đây là fcitx5 nhé, không phải fcitx đâu.....
> 
> Ubuntu có fcitx5-bamboo từ 22.10 đấy

Em cám ơn ạ, em tải fcitx5-bamboo từ repo thành công rồi.
Còn 1 câu hỏi nữa, làm sao để cho fcitx tự động chạy mỗi khi bật máy lên
Em đang sử dụng kubuntu

**Comment by wengxt** [comment]
error you hit need extra-cmake-modules
